version: 2

plugins:
  brakeman:
    enabled: true

  bundler-audit:
    enabled: true

  csslint:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript

  eslint:
    enabled: false        # Disabled due to lack of support for shared configs https://github.com/codeclimate/codeclimate-eslint/issues/86
    channel: "eslint-3"

  fixme:
    enabled: true

  markdownlint:
    enabled: true

  nodesecurity:
    enabled: false

  rubocop:
    enabled: false        # Disabled due to lack of support for inherit_gem https://github.com/codeclimate/codeclimate-eslint/issues/86