inherit_gem:
  rubocop-config-oharagroup:
    - default.yml
    - rails.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

# ------------------------------------------------------------
# Cops that rubocop disables by default, but we want to enable
# ------------------------------------------------------------

# Required for as_json methods
Style/OptionHash:
  Enabled: false

# ------------------------------------------------------------
# END disabled by default cops
# ------------------------------------------------------------
# Cops that rubocop enables by default, but we want to disable
# ------------------------------------------------------------

# Needed for update_all and update_column used in a few places
Rails/SkipsModelValidations:
  Enabled: false

# ------------------------------------------------------------
# END enabled by default cops
# ------------------------------------------------------------
# Cops that we want to reconfigure
# ------------------------------------------------------------

# Indent arrays consistently
Layout/IndentArray:
  EnforcedStyle: consistent

# ------------------------------------------------------------
# END reconfigured cops
# ------------------------------------------------------------