require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-factory_bot

inherit_gem:
  rubocop-config-oharagroup:
    - default.yml
    - performance.yml
    - rails.yml
    - rake.yml
    - rspec.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

# Can't fully qualify a private_constant
Lint/ConstantResolution:
  Ignore:
    - Frequency
    - FREQUENCIES
    - NUM_RESULTS
    - LEDGER_QUERY_OPTS

# Allow reading of ENV vars for authentication
Rails/EnvironmentVariableAccess:
  AllowReads: true

# Can't use :inverse_of due to self-referential and polymorphic associations
Rails/InverseOf:
  Enabled: false

# Needed for update_all and update_column used in a few places
Rails/SkipsModelValidations:
  Enabled: false