require:
  - rubocop-factory_bot
  - rubocop-rspec_rails

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  rubocop-config-oharagroup:
    - default.yml
    - factory_bot.yml
    - performance.yml
    - rails.yml
    - rake.yml
    - rspec_rails.yml
    - rspec.yml

AllCops:
  Exclude:
    - "bin/*"
    - "config/**/*"
    - "db/migrate/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "vendor/**/*"

# Can't fully qualify a private_constant
Lint/ConstantResolution:
  Ignore:
    - Frequency
    - FREQUENCIES
    - NUM_RESULTS

# Allow reading of ENV vars for authentication
Rails/EnvironmentVariableAccess:
  AllowReads: true

# Can't use :inverse_of due to self-referential and polymorphic associations
Rails/InverseOf:
  Enabled: false

# Needed for update_all and update_column used in a few places
Rails/SkipsModelValidations:
  Enabled: false
