require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rubocop-config-oharagroup:
    - default.yml
    - performance.yml
    - rails.yml
    - rspec.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

# Can't use :inverse_of due to self-referential and polymorphic associations
Rails/InverseOf:
  Enabled: false

# Needed for update_all and update_column used in a few places
Rails/SkipsModelValidations:
  Enabled: false