#!/bin/sh -e

# This entrypoint script is customised for use with Alpine Linux and Fly.io

# If the user is root
if [ $(id -u) -eq 0 ]; then
  # Set the swappiness level to 10
  sysctl --write vm.swappiness=10

	# Enable the swapfile
  swapon /swapfile

	# Switch to a non-root system user and re-execute the command
  exec su --shell /bin/sh loot --command "$0 $*"
fi

# Execute the script args as a command
$@