primary_region = "syd"
swap_size_mb = 512

[deploy]
	release_command = "bundle exec rake db:migrate"

[http_service]
	internal_port = 3000
	force_https = true
	min_machines_running = 1

	[http_service.concurrency]
		hard_limit = 100
		soft_limit = 90

	[[http_service.checks]]
		grace_period = "5s"
		interval = "10s"
		timeout = "2s"
		path = "/up"

[[statics]]
	guest_path = "/loot/public"
	url_prefix = "/"