[deploy]
	release_command = "bundle exec rake db:migrate"

[[statics]]
	guest_path = "/loot/public"
	url_prefix = "/"

[[services]]
	internal_port = 3000
	protocol = "tcp"

	[services.concurrency]
		hard_limit = 100
		soft_limit = 90

	[[services.ports]]
		force_https = true
		handlers = ["http"]
		port = 80

	[[services.ports]]
		handlers = ["tls", "http"]
		port = 443

	[[services.tcp_checks]]
		grace_period = "1s"
		interval = "15s"
		restart_limit = 0
		timeout = "2s"