config_version = "0"

[[source]]
name = "default"
default = true

[[plugin]]
name = "actionlint"

[[plugin]]
name = "brakeman"

[[plugin]]
name = "checkov"

[[plugin]]
name = "dotenv-linter"

[[plugin]]
name = "gitleaks"

[[plugin]]
name = "hadolint"

[[plugin]]
name = "markdownlint"

[[plugin]]
name = "osv-scanner"

[[plugin]]
name = "prettier"

[[plugin]]
name = "radarlint"

[[plugin]]
name = "ripgrep"

[[plugin]]
name = "shellcheck"

[[plugin]]
name = "shfmt"

[[plugin]]
name = "sqlfluff"

[[plugin]]
name = "trivy"

[[plugin]]
name = "trufflehog"

[[plugin]]
name = "yamllint"