// Vendor
import "jquery";
import "angular";
import "angular-mocks";

// Source
import "~/loot";

// Mocks
import "~/mocks";

// Tests
import "~/accounts/controllers/delete.test";
import "~/accounts/controllers/edit.test";
import "~/accounts/controllers/index.test";
import "~/accounts/controllers/reconcile.test";
import "~/accounts/models/account.test";
import "~/authentication/controllers/edit.test";
import "~/authentication/models/authentication.test";
import "~/categories/controllers/delete.test";
import "~/categories/controllers/edit.test";
import "~/categories/controllers/index.test";
import "~/categories/models/category.test";
import "~/loot/controllers/layout.test";
import "~/loot/providers/states.test";
import "~/loot/index.test";
import "~/og-components/og-favourite/directives/og-favourite.test";
import "~/og-components/og-input-autoselect/directives/og-input-autoselect.test";
import "~/og-components/og-input-calculator/directives/og-input-calculator.test";
import "~/og-components/og-input-currency/controllers/currency.test";
import "~/og-components/og-input-currency/directives/og-input-currency.test";
import "~/og-components/og-input-number/controllers/number.test";
import "~/og-components/og-input-number/directives/og-input-number.test";
import "~/og-components/og-loading-spinner/directives/og-loading-spinner.test";
import "~/og-components/og-lru-cache-factory/models/og-lru-cache-factory.test";
import "~/og-components/og-modal-alert/controllers/alert.test";
import "~/og-components/og-modal-confirm/controllers/confirm.test";
import "~/og-components/og-modal-error/services/og-modal-error.test";
import "~/og-components/og-navigator-serviceworker/services/og-navigator-serviceworker.test";
import "~/og-components/og-table-loading/directives/og-table-loading.test";
import "~/og-components/og-table-navigable/directives/og-table-navigable.test";
import "~/og-components/og-view-scroll/services/og-view-scroll.test";
import "~/payees/controllers/delete.test";
import "~/payees/controllers/edit.test";
import "~/payees/controllers/index.test";
import "~/payees/models/payee.test";
import "~/schedules/controllers/delete.test";
import "~/schedules/controllers/edit.test";
import "~/schedules/controllers/index.test";
import "~/schedules/filters/estimate.test";
import "~/schedules/models/schedule.test";
import "~/securities/controllers/delete.test";
import "~/securities/controllers/edit.test";
import "~/securities/controllers/index.test";
import "~/securities/models/security.test";
import "~/transactions/controllers/delete.test";
import "~/transactions/controllers/edit.test";
import "~/transactions/controllers/flag.test";
import "~/transactions/controllers/index.test";
import "~/transactions/directives/flag.test";
import "~/transactions/directives/status.test";
import "~/transactions/models/transaction.test";
